name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.9
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd fiduswriter
        mv ../travis/configuration.py ./
        pip3 install requests[security]
        pip3 install -r requirements.txt
        pip3 install -r dev-requirements.txt
        pip3 install coverage
         pip3 install coveralls
         coverage run manage.py setup --no-static
    - name: Run tests
      run: travis_retry coverage run --concurrency=multiprocessing manage.py test 
